name: docker-build

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: quay.io/andrijdavid/cpuminer:latest
    

      - name: Run Snyk to check Docker image for vulnerabilities
        id: snyk_scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: quay.io/andrijdavid/nym-mixnode:latest
          sarif: true
          args: --file=Dockerfile --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        if: steps.snyk_scan.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif